plugins {
    id 'java'
}

group = 'org.futurepages'
version = '4.2.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

sourceSets {
    main {
        java {
            srcDir 'src'
        }
        resources {
            srcDir 'src'
            exclude '**/*.java'
        }
    }
}

repositories {
    mavenCentral()  // Use Maven Central for dependency resolution
    // You can add other repositories if needed, e.g., JCenter, custom Maven repos, etc.
}

dependencies {
    implementation fileTree(
            dir: "lib",
            include: [
                    '*.jar',
                    'jai-1_1_3/*.jar',
                    'jee/*.jar',
                    'jasper_reports/*.jar',
                    'jersey/*.jar',
                    'hibernate-4.1.7.Final/required/*.jar',
                    'okhttp/*.jar',
                    'pdfbox-lib/*.jar',
                    'test/*.jar',
                    'jpegcodec/*.jar',

            ]
    )

    // new ones imported from central:
    implementation 'com.twelvemonkeys.imageio:imageio-webp:3.8.1'
    // end of imported from central.
}

