package modules.global.model.install.brasil;

import modules.global.model.entities.Pais;
import org.futurepages.core.persistence.Dao;

public class Paises  {

	public static void instalaTodos() {
		Dao.getInstance().save(new Pais("AFG", "Afeganistão"));
		Dao.getInstance().save(new Pais("ZAF", "África do Sul"));
		Dao.getInstance().save(new Pais("ALA", "Åland, Ilhas"));
		Dao.getInstance().save(new Pais("ALB", "Albânia"));
		Dao.getInstance().save(new Pais("DEU", "Alemanha"));
		Dao.getInstance().save(new Pais("AND", "Andorra"));
		Dao.getInstance().save(new Pais("AGO", "Angola"));
		Dao.getInstance().save(new Pais("AIA", "Anguilla"));
		Dao.getInstance().save(new Pais("ATA", "Antárctida"));
		Dao.getInstance().save(new Pais("ATG", "Antigua e Barbuda"));
		Dao.getInstance().save(new Pais("ANT", "Antilhas Holandesas"));
		Dao.getInstance().save(new Pais("SAU", "Arábia Saudita"));
		Dao.getInstance().save(new Pais("DZA", "Argélia"));
		Dao.getInstance().save(new Pais("ARG", "Argentina"));
		Dao.getInstance().save(new Pais("ARM", "Arménia"));
		Dao.getInstance().save(new Pais("ABW", "Aruba"));
		Dao.getInstance().save(new Pais("AUS", "Austrália"));
		Dao.getInstance().save(new Pais("AUT", "Áustria"));
		Dao.getInstance().save(new Pais("AZE", "Azerbeijão"));
		Dao.getInstance().save(new Pais("BHS", "Bahamas"));
		Dao.getInstance().save(new Pais("BHR", "Bahrain"));
		Dao.getInstance().save(new Pais("BGD", "Bangladesh"));
		Dao.getInstance().save(new Pais("BRB", "Barbados"));
		Dao.getInstance().save(new Pais("BEL", "Bélgica"));
		Dao.getInstance().save(new Pais("BLZ", "Belize"));
		Dao.getInstance().save(new Pais("BEN", "Benin"));
		Dao.getInstance().save(new Pais("BMU", "Bermuda"));
		Dao.getInstance().save(new Pais("BLR", "Bielo-Rússia"));
		Dao.getInstance().save(new Pais("BOL", "Bolívia"));
		Dao.getInstance().save(new Pais("BIH", "Bósnia-Herzegovina"));
		Dao.getInstance().save(new Pais("BWA", "Botswana"));
		Dao.getInstance().save(new Pais("BVT", "Bouvet, Ilha"));
		Dao.getInstance().save(new Pais("BRA", "Brasil"));
		Dao.getInstance().save(new Pais("BRN", "Brunei"));
		Dao.getInstance().save(new Pais("BGR", "Bulgária"));
		Dao.getInstance().save(new Pais("BFA", "Burkina Faso"));
		Dao.getInstance().save(new Pais("BDI", "Burundi"));
		Dao.getInstance().save(new Pais("BTN", "Butão"));
		Dao.getInstance().save(new Pais("CPV", "Cabo Verde"));
		Dao.getInstance().save(new Pais("KHM", "Cambodja"));
		Dao.getInstance().save(new Pais("CMR", "Camarões"));
		Dao.getInstance().save(new Pais("CAN", "Canadá"));
		Dao.getInstance().save(new Pais("CYM", "Cayman, Ilhas"));
		Dao.getInstance().save(new Pais("KAZ", "Cazaquistão"));
		Dao.getInstance().save(new Pais("CAF", "Centro-africana, República"));
		Dao.getInstance().save(new Pais("TCD", "Chade"));
		Dao.getInstance().save(new Pais("CZE", "Checa, República"));
		Dao.getInstance().save(new Pais("CHL", "Chile"));
		Dao.getInstance().save(new Pais("CHN", "China"));
		Dao.getInstance().save(new Pais("CYP", "Chipre"));
		Dao.getInstance().save(new Pais("CXR", "Christmas, Ilha"));
		Dao.getInstance().save(new Pais("CCK", "Cocos, Ilhas"));
		Dao.getInstance().save(new Pais("COL", "Colômbia"));
		Dao.getInstance().save(new Pais("COM", "Comores"));
		Dao.getInstance().save(new Pais("COG", "Congo, República do"));
		Dao.getInstance().save(new Pais("COD", "Congo, República Democrática do"));
		Dao.getInstance().save(new Pais("KOR", "Coreia do Sul"));
		Dao.getInstance().save(new Pais("PRK", "Coreia do Norte"));
		Dao.getInstance().save(new Pais("CIV", "Costa do Marfim"));
		Dao.getInstance().save(new Pais("CRI", "Costa Rica"));
		Dao.getInstance().save(new Pais("HRV", "Croácia"));
		Dao.getInstance().save(new Pais("CUB", "Cuba"));
		Dao.getInstance().save(new Pais("DNK", "Dinamarca"));
		Dao.getInstance().save(new Pais("DJI", "Djibouti"));
		Dao.getInstance().save(new Pais("DMA", "Dominica"));
		Dao.getInstance().save(new Pais("DOM", "Dominicana, República"));
		Dao.getInstance().save(new Pais("EGY", "Egipto"));
		Dao.getInstance().save(new Pais("SLV", "El Salvador"));
		Dao.getInstance().save(new Pais("ARE", "Emiratos Árabes Unidos"));
		Dao.getInstance().save(new Pais("ECU", "Equador"));
		Dao.getInstance().save(new Pais("ERI", "Eritreia"));
		Dao.getInstance().save(new Pais("STD", "Escócia"));
		Dao.getInstance().save(new Pais("SVK", "Eslováquia"));
		Dao.getInstance().save(new Pais("SVN", "Eslovénia"));
		Dao.getInstance().save(new Pais("ESP", "Espanha"));
		Dao.getInstance().save(new Pais("USA", "Estados Unidos da América"));
		Dao.getInstance().save(new Pais("EST", "Estónia"));
		Dao.getInstance().save(new Pais("ETH", "Etiópia"));
		Dao.getInstance().save(new Pais("FRO", "Faroe, Ilhas"));
		Dao.getInstance().save(new Pais("FJI", "Fiji"));
		Dao.getInstance().save(new Pais("PHL", "Filipinas"));
		Dao.getInstance().save(new Pais("FIN", "Finlândia"));
		Dao.getInstance().save(new Pais("FRA", "França"));
		Dao.getInstance().save(new Pais("GAB", "Gabão"));
		Dao.getInstance().save(new Pais("WLS", "Gales, País de"));
		Dao.getInstance().save(new Pais("GMB", "Gâmbia"));
		Dao.getInstance().save(new Pais("GHA", "Gana"));
		Dao.getInstance().save(new Pais("GEO", "Geórgia"));
		Dao.getInstance().save(new Pais("SGS", "Geórgia do Sul e Sandwich do Sul, Ilhas"));
		Dao.getInstance().save(new Pais("GIB", "Gibraltar"));
		Dao.getInstance().save(new Pais("GRC", "Grécia"));
		Dao.getInstance().save(new Pais("GRD", "Grenada"));
		Dao.getInstance().save(new Pais("GRL", "Gronelândia"));
		Dao.getInstance().save(new Pais("GLP", "Guadeloupe"));
		Dao.getInstance().save(new Pais("GUM", "Guam"));
		Dao.getInstance().save(new Pais("GTM", "Guatemala"));
		Dao.getInstance().save(new Pais("GGY", "Guernsey"));
		Dao.getInstance().save(new Pais("GUY", "Guiana"));
		Dao.getInstance().save(new Pais("GUF", "Guiana Francesa"));
		Dao.getInstance().save(new Pais("GNB", "Guiné-Bissau"));
		Dao.getInstance().save(new Pais("GIN", "Guiné-Conacri"));
		Dao.getInstance().save(new Pais("GNQ", "Guiné Equatorial"));
		Dao.getInstance().save(new Pais("HTI", "Haiti"));
		Dao.getInstance().save(new Pais("HMD", "Heard e Ilhas McDonald, Ilha"));
		Dao.getInstance().save(new Pais("HND", "Honduras"));
		Dao.getInstance().save(new Pais("HKG", "Hong Kong"));
		Dao.getInstance().save(new Pais("HUN", "Hungria"));
		Dao.getInstance().save(new Pais("YEM", "Iémen"));
		Dao.getInstance().save(new Pais("IND", "Índia"));
		Dao.getInstance().save(new Pais("IDN", "Indonésia"));
		Dao.getInstance().save(new Pais("IRQ", "Iraque"));
		Dao.getInstance().save(new Pais("IRN", "Irão"));
		Dao.getInstance().save(new Pais("IRL", "Irlanda"));
		Dao.getInstance().save(new Pais("ISL", "Islândia"));
		Dao.getInstance().save(new Pais("ISR", "Israel"));
		Dao.getInstance().save(new Pais("ITA", "Itália"));
		Dao.getInstance().save(new Pais("JAM", "Jamaica"));
		Dao.getInstance().save(new Pais("JPN", "Japão"));
		Dao.getInstance().save(new Pais("JEY", "Jersey"));
		Dao.getInstance().save(new Pais("JOR", "Jordânia"));
		Dao.getInstance().save(new Pais("KIR", "Kiribati"));
		Dao.getInstance().save(new Pais("KWT", "Kuwait"));
		Dao.getInstance().save(new Pais("LAO", "Laos"));
		Dao.getInstance().save(new Pais("LSO", "Lesoto"));
		Dao.getInstance().save(new Pais("LVA", "Letónia"));
		Dao.getInstance().save(new Pais("LBN", "Líbano"));
		Dao.getInstance().save(new Pais("LBR", "Libéria"));
		Dao.getInstance().save(new Pais("LBY", "Líbia"));
		Dao.getInstance().save(new Pais("LIE", "Liechtenstein"));
		Dao.getInstance().save(new Pais("LTU", "Lituânia"));
		Dao.getInstance().save(new Pais("LUX", "Luxemburgo"));
		Dao.getInstance().save(new Pais("MAC", "Macau"));
		Dao.getInstance().save(new Pais("MKD", "Macedónia, República da"));
		Dao.getInstance().save(new Pais("MDG", "Madagáscar"));
		Dao.getInstance().save(new Pais("MYS", "Malásia"));
		Dao.getInstance().save(new Pais("MWI", "Malawi"));
		Dao.getInstance().save(new Pais("MDV", "Maldivas"));
		Dao.getInstance().save(new Pais("MLI", "Mali"));
		Dao.getInstance().save(new Pais("MLT", "Malta"));
		Dao.getInstance().save(new Pais("FLK", "Malvinas, Ilhas"));
		Dao.getInstance().save(new Pais("IMN", "Man, Ilha de"));
		Dao.getInstance().save(new Pais("MNP", "Marianas Setentrionais"));
		Dao.getInstance().save(new Pais("MAR", "Marrocos"));
		Dao.getInstance().save(new Pais("MHL", "Marshall, Ilhas"));
		Dao.getInstance().save(new Pais("MTQ", "Martinica"));
		Dao.getInstance().save(new Pais("MUS", "Maurícia"));
		Dao.getInstance().save(new Pais("MRT", "Mauritânia"));
		Dao.getInstance().save(new Pais("MYT", "Mayotte"));
		Dao.getInstance().save(new Pais("UMI", "Menores Distantes dos Estados Unidos, Ilhas"));
		Dao.getInstance().save(new Pais("MEX", "México"));
		Dao.getInstance().save(new Pais("MMR", "Myanmar"));
		Dao.getInstance().save(new Pais("FSM", "Micronésia, Estados Federados da"));
		Dao.getInstance().save(new Pais("MOZ", "Moçambique"));
		Dao.getInstance().save(new Pais("MDA", "Moldávia"));
		Dao.getInstance().save(new Pais("MCO", "Mónaco"));
		Dao.getInstance().save(new Pais("MNG", "Mongólia"));
		Dao.getInstance().save(new Pais("MNE", "Montenegro"));
		Dao.getInstance().save(new Pais("MSR", "Montserrat"));
		Dao.getInstance().save(new Pais("NAM", "Namíbia"));
		Dao.getInstance().save(new Pais("NRU", "Nauru"));
		Dao.getInstance().save(new Pais("NPL", "Nepal"));
		Dao.getInstance().save(new Pais("NIC", "Nicarágua"));
		Dao.getInstance().save(new Pais("NER", "Níger"));
		Dao.getInstance().save(new Pais("NGA", "Nigéria"));
		Dao.getInstance().save(new Pais("NIU", "Niue"));
		Dao.getInstance().save(new Pais("NFK", "Norfolk, Ilha"));
		Dao.getInstance().save(new Pais("NOR", "Noruega"));
		Dao.getInstance().save(new Pais("NCL", "Nova Caledónia"));
		Dao.getInstance().save(new Pais("NZL", "Nova Zelândia"));
		Dao.getInstance().save(new Pais("OMN", "Oman"));
		Dao.getInstance().save(new Pais("NLD", "Holanda"));
		Dao.getInstance().save(new Pais("PLW", "Palau"));
		Dao.getInstance().save(new Pais("PSE", "Palestina"));
		Dao.getInstance().save(new Pais("PAN", "Panamá"));
		Dao.getInstance().save(new Pais("PNG", "Papua-Nova Guiné"));
		Dao.getInstance().save(new Pais("PAK", "Paquistão"));
		Dao.getInstance().save(new Pais("PRY", "Paraguai"));
		Dao.getInstance().save(new Pais("PER", "Peru"));
		Dao.getInstance().save(new Pais("PCN", "Pitcairn"));
		Dao.getInstance().save(new Pais("PYF", "Polinésia Francesa"));
		Dao.getInstance().save(new Pais("POL", "Polónia"));
		Dao.getInstance().save(new Pais("PRI", "Porto Rico"));
		Dao.getInstance().save(new Pais("PRT", "Portugal"));
		Dao.getInstance().save(new Pais("QAT", "Qatar"));
		Dao.getInstance().save(new Pais("KEN", "Quénia"));
		Dao.getInstance().save(new Pais("KGZ", "Quirguistão"));
		Dao.getInstance().save(new Pais("GBR", "Reino Unido da Grã-Bretanha e Irlanda do Norte"));
		Dao.getInstance().save(new Pais("REU", "Reunião"));
		Dao.getInstance().save(new Pais("ROU", "Roménia"));
		Dao.getInstance().save(new Pais("RWA", "Ruanda"));
		Dao.getInstance().save(new Pais("RUS", "Rússia"));
		Dao.getInstance().save(new Pais("ESH", "Saara Ocidental"));
		Dao.getInstance().save(new Pais("ASM", "Samoa Americana"));
		Dao.getInstance().save(new Pais("WSM", "Samoa Ocidental"));
		Dao.getInstance().save(new Pais("SPM", "Saint Pierre et Miquelon"));
		Dao.getInstance().save(new Pais("SLB", "Salomão, Ilhas"));
		Dao.getInstance().save(new Pais("KNA", "São Cristóvão e Névis"));
		Dao.getInstance().save(new Pais("SMR", "San Marino"));
		Dao.getInstance().save(new Pais("STP", "São Tomé e Príncipe"));
		Dao.getInstance().save(new Pais("VCT", "São Vicente e Granadinas"));
		Dao.getInstance().save(new Pais("SHN", "Santa Helena"));
		Dao.getInstance().save(new Pais("LCA", "Santa Lúcia"));
		Dao.getInstance().save(new Pais("SEN", "Senegal"));
		Dao.getInstance().save(new Pais("SLE", "Serra Leoa"));
		Dao.getInstance().save(new Pais("SRB", "Sérvia"));
		Dao.getInstance().save(new Pais("SYC", "Seychelles"));
		Dao.getInstance().save(new Pais("SGP", "Singapura"));
		Dao.getInstance().save(new Pais("SYR", "Síria"));
		Dao.getInstance().save(new Pais("SOM", "Somália"));
		Dao.getInstance().save(new Pais("LKA", "Sri Lanka"));
		Dao.getInstance().save(new Pais("SWZ", "Suazilândia"));
		Dao.getInstance().save(new Pais("SDN", "Sudão"));
		Dao.getInstance().save(new Pais("SWE", "Suécia"));
		Dao.getInstance().save(new Pais("CHE", "Suíça"));
		Dao.getInstance().save(new Pais("SUR", "Suriname"));
		Dao.getInstance().save(new Pais("SJM", "Svalbard e Jan Mayen"));
		Dao.getInstance().save(new Pais("THA", "Tailândia"));
		Dao.getInstance().save(new Pais("TWN", "Taiwan"));
		Dao.getInstance().save(new Pais("TJK", "Tajiquistão"));
		Dao.getInstance().save(new Pais("TZA", "Tanzânia"));
		Dao.getInstance().save(new Pais("ATF", "Terras Austrais e Antárticas Francesas"));
		Dao.getInstance().save(new Pais("IOT", "Território Britânico do Oceano Índico"));
		Dao.getInstance().save(new Pais("TLS", "Timor-Leste"));
		Dao.getInstance().save(new Pais("TGO", "Togo"));
		Dao.getInstance().save(new Pais("TKL", "Toquelau"));
		Dao.getInstance().save(new Pais("TON", "Tonga"));
		Dao.getInstance().save(new Pais("TTO", "Trindade e Tobago"));
		Dao.getInstance().save(new Pais("TUN", "Tunísia"));
		Dao.getInstance().save(new Pais("TCA", "Turks e Caicos"));
		Dao.getInstance().save(new Pais("TKM", "Turquemenistão"));
		Dao.getInstance().save(new Pais("TUR", "Turquia"));
		Dao.getInstance().save(new Pais("TUV", "Tuvalu"));
		Dao.getInstance().save(new Pais("UKR", "Ucrânia"));
		Dao.getInstance().save(new Pais("UGA", "Uganda"));
		Dao.getInstance().save(new Pais("URY", "Uruguai"));
		Dao.getInstance().save(new Pais("UZB", "Usbequistão"));
		Dao.getInstance().save(new Pais("VUT", "Vanuatu"));
		Dao.getInstance().save(new Pais("VAT", "Vaticano"));
		Dao.getInstance().save(new Pais("VEN", "Venezuela"));
		Dao.getInstance().save(new Pais("VNM", "Vietname"));
		Dao.getInstance().save(new Pais("VIR", "Virgens Americanas, Ilhas"));
		Dao.getInstance().save(new Pais("VGB", "Virgens Britânicas, Ilhas"));
		Dao.getInstance().save(new Pais("WLF", "Wallis e Futuna"));
		Dao.getInstance().save(new Pais("ZMB", "Zâmbia"));
		Dao.getInstance().save(new Pais("ZWE", "Zimbabwe"));
	}
}